# Generated by Django 3.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BalanceCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('photo_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'balance_certifications',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], max_length=10)),
                ('transaction_date', models.DateField()),
                ('amount', models.PositiveBigIntegerField()),
                ('photo_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'budget_records',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRecordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.PositiveBigIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ppanzziri.budgetrecord')),
            ],
            options={
                'db_table': 'budget_record_tags',
                'ordering': ['-amount', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEffectiveSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('segment_amount', models.PositiveBigIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effective_segments', to='ppanzziri.budgetrecord')),
            ],
            options={
                'db_table': 'budget_effective_segments',
                'ordering': ['effective_from', 'id'],
            },
        ),
    ]
