"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

SESSION_COOKIE_DOMAIN = os.environ.get('DOMAIN'),
CSRF_COOKIE_DOMAIN = os.environ.get('DOMAIN'),

CSRF_TRUSTED_ORIGINS = [
    os.environ.get('FRONT_DOMAIN'),
    os.environ.get('BACK_ADDRESS')
]