# Generated by Django 3.2.5 on 2024-07-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=16, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='출처')),
                ('purpose', models.CharField(max_length=200, verbose_name='목적')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=300, verbose_name='내용')),
                ('order', models.IntegerField(blank=True, default=20, verbose_name='순서')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_sentence', to='cowriter.essay', verbose_name='에세이')),
            ],
        ),
        migrations.CreateModel(
            name='TopciSentenceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_sentence', to='cowriter.keyword', verbose_name='키워드')),
                ('topic_senctence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keyword', to='cowriter.topicsentence', verbose_name='중심 문장')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject', to='cowriter.keyword', verbose_name='키워드')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keyword', to='cowriter.subject', verbose_name='주제')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=True, verbose_name='선택')),
                ('topic_sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase', to='cowriter.topicsentence', verbose_name='중심 문장')),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='에세이', to='cowriter.subject', verbose_name='주제'),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=16, verbose_name='사용자')),
                ('keyword1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edge_start', to='cowriter.keyword', verbose_name='키워드1')),
                ('keyword2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edge_end', to='cowriter.keyword', verbose_name='키워드2')),
            ],
        ),
    ]
