# Generated by Django 3.2.5 on 2024-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowriter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_url',
            field=models.TextField(blank=True, db_column='SUBJECT_URL', verbose_name='주제URL'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_purpose',
            field=models.CharField(blank=True, db_column='SUBJECT_PURPOSE', max_length=50, verbose_name='목적'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_title',
            field=models.CharField(blank=True, db_column='SUBJECT_TITLE', max_length=200, verbose_name='제목'),
        ),
    ]
