# Generated by Django 3.2.5 on 2021-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('generation', models.FloatField(blank=True, default=20)),
                ('imgGoogleId', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detgori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('googleId', models.CharField(blank=True, max_length=200, verbose_name='구글id')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detgori', to=settings.AUTH_USER_MODEL, verbose_name='댓거리 작성자')),
            ],
        ),
        migrations.CreateModel(
            name='DetgoriComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('text', models.CharField(max_length=200, verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='댓글 작성자')),
                ('parentDetgori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hannuri.detgori', verbose_name='댓거리')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('ALL', '전체 공개'), ('1MEMBER', '한누리 공개'), ('2MEMBER', '두누리 공개'), ('ALLMEMBER', '전체 학회원 공개'), ('CLOSED', '비공개')], max_length=10, verbose_name='공개범위')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='내용')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2020, verbose_name='연도')),
                ('semester', models.PositiveIntegerField(default=1, verbose_name='학기')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('leader', models.CharField(max_length=50, verbose_name='회장')),
                ('sessioner', models.CharField(max_length=50, verbose_name='학술부장')),
                ('socializer', models.CharField(max_length=50, verbose_name='기획부장')),
                ('googleFolderId', models.CharField(blank=True, max_length=200, verbose_name='구글드라이브 폴더ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('week', models.IntegerField(default=1, verbose_name='주차')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('googleFolderId', models.CharField(blank=True, max_length=200, verbose_name='구글드라이브 폴더ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='hannuri.season', verbose_name='학기')),
            ],
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='활동 제목')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('summary', models.TextField(verbose_name='활동 요약')),
                ('googleFolderId', models.CharField(max_length=200, verbose_name='구글드라이브 폴더ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialActivity', to='hannuri.season', verbose_name='학기')),
            ],
        ),
        migrations.CreateModel(
            name='SessionReadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('googleId', models.CharField(blank=True, max_length=200, verbose_name='구글id')),
                ('parentSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readfile', to='hannuri.session')),
            ],
        ),
        migrations.CreateModel(
            name='DetgoriCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('text', models.CharField(max_length=200, verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대댓글 작성자')),
                ('parentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReplys', to='hannuri.detgoricomment', verbose_name='댓글')),
            ],
        ),
        migrations.AddField(
            model_name='detgori',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detgori', to='hannuri.session', verbose_name='세션'),
        ),
    ]
