# Generated by Django 3.2.5 on 2021-07-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='generation',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
