# Generated by Django 3.2.5 on 2021-07-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0004_alter_user_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='detgori',
            name='words',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True, verbose_name='구글 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='generation',
            field=models.IntegerField(blank=True, default=20, verbose_name='기수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='활동 허가'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='임원진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='이름'),
        ),
    ]
