# Generated by Django 3.2.5 on 2021-08-11 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0005_auto_20210731_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='내용')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('isRoot', models.BooleanField(default=False)),
                ('RelatedNotes', models.ManyToManyField(related_name='_hannuri_freenote_RelatedNotes_+', to='hannuri.FreeNote')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeNote', to=settings.AUTH_USER_MODEL, verbose_name='대댓글 작성자')),
            ],
        ),
    ]
