# Generated by Django 3.2.5 on 2021-08-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0007_rename_text_freenote_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freenote',
            old_name='description',
            new_name='text',
        ),
    ]
