# Generated by Django 3.2.5 on 2021-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0008_rename_description_freenote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freenote',
            name='RelatedNotes',
            field=models.ManyToManyField(blank=True, related_name='_hannuri_freenote_RelatedNotes_+', to='hannuri.FreeNote'),
        ),
    ]
