# Generated by Django 3.2.5 on 2021-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0009_alter_freenote_relatednotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freenote',
            name='RelatedNotes',
        ),
        migrations.AddField(
            model_name='freenote',
            name='related_notes',
            field=models.ManyToManyField(blank=True, related_name='_hannuri_freenote_related_notes_+', to='hannuri.FreeNote'),
        ),
    ]
