# Generated by Django 3.2.5 on 2021-08-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0010_auto_20210811_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freenote',
            name='isRoot',
        ),
        migrations.RemoveField(
            model_name='freenote',
            name='related_notes',
        ),
        migrations.AddField(
            model_name='freenote',
            name='lineFrom',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='freenote',
            name='lineTo',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='freenote',
            name='page',
            field=models.IntegerField(default=-1),
        ),
    ]
