# Generated by Django 3.2.5 on 2021-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0011_auto_20210811_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freenote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='freenote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='freenote',
            name='lineFrom',
        ),
        migrations.RemoveField(
            model_name='freenote',
            name='lineTo',
        ),
        migrations.AddField(
            model_name='freenote',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='freenote',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
