# Generated by Django 3.2.5 on 2021-08-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0013_socialactivityimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imgGoogleId',
            new_name='color',
        ),
    ]
