# Generated by Django 3.2.5 on 2021-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0014_rename_imggoogleid_user_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '1. 공지사항'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': '학기', 'verbose_name_plural': '2. 학기'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '세션', 'verbose_name_plural': '3. 세션'},
        ),
        migrations.AlterModelOptions(
            name='socialactivity',
            options={'verbose_name': '기획활동', 'verbose_name_plural': '4. 기획활동'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '학회원', 'verbose_name_plural': '0. 학회원'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scope',
        ),
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, default='#000080', max_length=200, null=True),
        ),
    ]
