# Generated by Django 3.2.5 on 2021-08-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0015_auto_20210817_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='detgori',
            name='pdf',
            field=models.FileField(blank=True, upload_to='detgori/'),
        ),
        migrations.AlterField(
            model_name='sessionreadfile',
            name='pdf',
            field=models.FileField(blank=True, upload_to='session/'),
        ),
        migrations.AlterField(
            model_name='socialactivityimg',
            name='img',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
