# Generated by Django 3.2.5 on 2021-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0016_auto_20210822_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='현재 진행 학기'),
        ),
    ]
