# Generated by Django 3.2.5 on 2021-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0017_season_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissionId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
