# Generated by Django 3.2.5 on 2021-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0018_user_permissionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='현재 진행 세션(메인 화면 표시)'),
        ),
    ]
