# Generated by Django 3.2.5 on 2021-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0019_session_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialactivity',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='임원진'),
        ),
    ]
