# Generated by Django 3.2.5 on 2021-09-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0020_auto_20210827_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freenote',
            options={'verbose_name': '공책', 'verbose_name_plural': '5. 메타동방-공책'},
        ),
        migrations.AddField(
            model_name='user',
            name='organizerPermissionId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
