# Generated by Django 3.2.5 on 2021-09-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0022_rename_organizerpermissionid_user_writerpermissionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='writerPermissionId',
        ),
        migrations.AddField(
            model_name='user',
            name='writerPermissioned',
            field=models.BooleanField(default=False),
        ),
    ]
