# Generated by Django 3.2.5 on 2022-03-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0024_user_actingseason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detgoricommentreply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='detgoricommentreply',
            name='parentComment',
        ),
        migrations.RemoveField(
            model_name='socialactivity',
            name='season',
        ),
        migrations.RemoveField(
            model_name='socialactivityimg',
            name='parentSocialActivity',
        ),
        migrations.AlterModelOptions(
            name='freenote',
            options={'verbose_name': '공책', 'verbose_name_plural': '4. 메타동방-공책'},
        ),
        migrations.DeleteModel(
            name='DetgoriComment',
        ),
        migrations.DeleteModel(
            name='DetgoriCommentReply',
        ),
        migrations.DeleteModel(
            name='SocialActivity',
        ),
        migrations.DeleteModel(
            name='SocialActivityImg',
        ),
    ]
