# Generated by Django 3.2.5 on 2022-03-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0025_auto_20220312_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='detgori',
            name='pureText',
            field=models.TextField(blank=True),
        ),
    ]
