# Generated by Django 3.2.5 on 2022-03-14 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0026_detgori_puretext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detgori',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detgori', to=settings.AUTH_USER_MODEL, verbose_name='댓거리 작성자'),
        ),
        migrations.AlterField(
            model_name='detgori',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detgori', to='hannuri.session', verbose_name='세션'),
        ),
        migrations.AlterField(
            model_name='session',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='hannuri.season', verbose_name='학기'),
        ),
        migrations.AlterField(
            model_name='sessionreadfile',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readfile', to='hannuri.session'),
        ),
    ]
