# Generated by Django 3.2.5 on 2022-05-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0027_auto_20220314_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='act_seasons',
            field=models.ManyToManyField(to='hannuri.Season'),
        ),
        migrations.AlterField(
            model_name='sessionreadfile',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readfile', to='hannuri.session'),
        ),
    ]
