# Generated by Django 3.2.5 on 2022-05-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0028_auto_20220502_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actingSeason',
        ),
    ]
