# Generated by Django 3.2.5 on 2022-12-02 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0030_season_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetgoriReadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(verbose_name='reading time')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='읽은 날짜')),
                ('detgori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hannuri.detgori', verbose_name='읽은 댓거리')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='읽은 사람')),
            ],
        ),
    ]
