# Generated by Django 3.2.5 on 2023-03-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0032_auto_20230317_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeNote',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '학회원', 'verbose_name_plural': '1. 학회원'},
        ),
    ]
