# Generated by Django 3.2.5 on 2024-02-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0033_auto_20230317_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detgori',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='sessionreadfile',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='detgori',
            name='googleId',
            field=models.CharField(blank=True, max_length=200, verbose_name='파일id'),
        ),
        migrations.AlterField(
            model_name='sessionreadfile',
            name='googleId',
            field=models.CharField(blank=True, max_length=200, verbose_name='파일id'),
        ),
    ]
