# Generated by Django 3.2.5 on 2024-02-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0034_auto_20240212_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreadfile',
            name='pdf',
            field=models.FileField(blank=True, upload_to='session/'),
        ),
    ]
