# Generated by Django 3.2.5 on 2024-05-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0035_sessionreadfile_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetgoriOnProcessingDerived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detgori_id', models.IntegerField(verbose_name='댓거리id')),
            ],
        ),
    ]
