# Generated by Django 3.2.5 on 2025-01-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hannuri', '0036_detgorionprocessingderived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField(blank=True, verbose_name='순서')),
                ('content', models.TextField(blank=True)),
                ('detgori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentence', to='hannuri.detgori', verbose_name='댓거리')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='단어')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='단어 언급 횟수')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word', to='hannuri.sentence', verbose_name='문장')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentence', to='hannuri.word', verbose_name='단어')),
            ],
        ),
    ]
